INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (5, 'ANTIOQUIA', '05', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (8, 'ATLANTICO', '08', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (11, 'BOGOTA, D.C.', '11', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (13, 'BOLIVAR', '13', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (15, 'BOYACA', '15', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (17, 'CALDAS', '17', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (18, 'CAQUETA', '18', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (19, 'CAUCA', '19', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (20, 'CESAR', '20', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (23, 'CORDOBA', '23', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (25, 'CUNDINAMARCA', '25', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (27, 'CHOCO', '27', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (41, 'HUILA', '41', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (44, 'LA GUAJIRA', '44', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (47, 'MAGDALENA', '47', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (50, 'META', '50', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (52, 'NARIÑO', '52', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (54, 'NORTE DE SANTANDER', '54', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (63, 'QUINDIO', '63', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (66, 'RISARALDA', '66', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (68, 'SANTANDER', '68', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (70, 'SUCRE', '70', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (73, 'TOLIMA', '73', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (76, 'VALLE DEL CAUCA', '76', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (81, 'ARAUCA', '81', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (85, 'CASANARE', '85', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (86, 'PUTUMAYO', '86', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (88, 'ARCHIPIELAGO DE SAN ANDRES PROVIDENCIA Y SANTA CATALINA', '88', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (91, 'AMAZONAS', '91', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (94, 'GUAINIA', '94', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (95, 'GUAVIARE', '95', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (97, 'VAUPES', '97', NULL, NULL);
INSERT INTO `departamentos` (`id`, `nombre`, `codigo`, `created_at`, `updated_at`) VALUES (99, 'VICHADA', '99', NULL, NULL);
